### ISSUE TITLE
Cross compatibility with Quillnote database

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Notes#28]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

In the password managers ecosystem there is .kdbx common database format (shared between open source apps). In KeePass family every developer can develop its app but the database format is always the .kdbx, common for all.

I propose something similar: the quillnote database format is universal.
I ask for an implementation in Fossify Note.
So Fossify Note can entering in "Quill" family notebook apps.

### Why do you want this feature?

To use always my database in every platform, changing only the app.

### Additional information

https://quillpad.github.io (open source)

**Comment by naveensingh** [comment]
> the quillnote database format is universal

source?

**Comment by Violet-RM** [comment]
> > the quillnote database format is universal
> 
> source?

I think they were proposing the establishment of the quillnote database format as a universal standard rather than claiming it already is one

**Comment by naveensingh** [comment]
I'm closing this for now as not-on-the-foreseeable-roadmap, maybe someday.

**Comment by kaoneko** [comment]
Quillpad uses Markdown, which is already a widespread standard, so it would make more sense to ask for/implement Markdown rendering. 

Lots of apps directly open from and write to Markdown files in the file system, making it very easy to share notes between them.

Fossify Notes can already link a note to a text file. A Markdown file is just a text file, usually with the `.md` extension. So this: 

> To use always my database in every platform, changing only the app.

..should already be possible with Fossify Notes. And while it doesn't render Markdown, it should still look parsable to human eyes, since that's the whole idea of Markdown.
